import React from 'react'

function StaffHomeContainer() {
	return (
		<div className="flex-1 bg-accent m-3 p-5 border border-[#D2D2D2] rounded-xl">
			<div>
				<div className='flex flex-col items-center'>
					<h1 className='text-3xl font-bold'>Welcome to the Staff Dashboard!</h1>
					<p className='text-lg italic font-semibold'>This guide provides clear and intuitive instructions to help you efficiently use the features available on each page.</p>
				</div>
				<div className='mx-5 my-3 flex flex-col gap-5'>
					<div>
						<h2 className='guideH2'>1. Submit Data</h2>
						<div className='ml-5'>
							<p><span className='font-semibold'>Purpose:</span> The Submit Data page allows you to upload files for analytics generation.</p>
							<p className='font-semibold'>Steps:</p>
							<ol>
								<li>1. Navigate to the Submit Data page.</li>
								<li>2. Click the Select File button.</li>
								<li>3. Select the data file(.csv files only) from your device.</li>
								<li>4. Click the Upload File Button to upload the file. The system will process your data and generate analytics based on it.</li>
							</ol>
						</div>
					</div>

					<div>
						<h2 className='guideH2'>2. View Analytics</h2>
						<div className='ml-5'>
							<p><span className='font-semibold'>Purpose:</span> The View Analytics page displays a list of analytics generated by you and others.</p>
							<p className='font-semibold'>Layout:</p>
							<ul className='list-disc ml-5'>
								<li>Left Section: Shows analytics generated by you.</li>
								<li>Right Section: Displays analytics created by other staff members.</li>
							</ul>
							<p className='font-semibold'>Steps:</p>
							<ol>
								<li>1. Navigate to the View Analytics page.</li>
								<li>2. Browse through the analytics in the respective sections.</li>
							</ol>
						</div>
					</div>

					<div>
						<h2 className='guideH2'>3. View Reports</h2>
						<div className='ml-5'>
							<p><span className='font-semibold'>Purpose:</span> The View Reports page allows you to access reports that have been previously generated.</p>
							<p className='font-semibold'>Steps:</p>
							<ol>
								<li>1. Navigate to the View Reports page.</li>
								<li>2. Use the provided filters to refine your search:</li>
								<ul className='ml-10 list-disc'>
									<li>Department: Select the department related to the report.</li>
									<li>Category: Choose the relevant category for the report.</li>
								</ul>
								<li>3. Review the filtered list of reports.</li>
								<li>4. Click on a report to view its contents and details.</li>
							</ol>
						</div>
					</div>

					<div>
						<h2 className='guideH2'>General Tips</h2>
						<ul className='ml-5 list-disc'>
							<li>Ensure that the data you upload is accurate and complete to generate meaningful analytics.</li>
							<li>Use the filters in the View Reports page to quickly find specific reports.</li>
							<li>For any issues or questions, contact your administrator.</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	)
}

export default StaffHomeContainer