import React from 'react'
import { Link } from 'react-router-dom'

function InstitutionHomeContainer() {
	return (
		<div className="flex-1 bg-accent m-3 p-5 border border-[#D2D2D2] rounded-xl">
			<div>
				<div className='flex flex-col items-center'>
					<h1 className='text-3xl font-bold'>Welcome to the Admin Dashboard!</h1>
					<p className='text-lg italic font-semibold'>This guide provides step-by-step instructions to help you navigate and use the features available on each page effectively.</p>
				</div>
				<div className='mx-5 my-3 flex flex-col gap-5'>
					<div>
						<h2 className='guideH2'>1. Analytics</h2>
						<p>The Analytics page is divided into two tabs:</p>
						<ul>
							<li>
								<h3 className='guideH3'>1.1 Upload Data</h3>
								<div className='ml-5'>
									<p><span className='font-semibold'>Purpose:</span> Upload data files to generate analytics(.csv files only)</p>
									<p className='font-semibold'>Steps:</p>
									<ol>
										<li>1. Navigate to the Upload Data tab.</li>
										<li>2. Click the Select File button.</li>
										<li>3. Select the department and category of analytics to be generated and then select the desired data file(.csv file only) from your computer.</li>
										<li>4. Click Upload File Button to upload the file. The system will process the file and generate analytics.</li>
									</ol>
								</div>
							</li>
							<li>
								<h3 className='guideH3'>1.2 Approve Analytics</h3>
								<div className='ml-5'>
									<p><span className='font-semibold'>Purpose:</span> Approve or reject analytics generated by staff members.</p>
									<p className='font-semibold'>Steps:</p>
									<ol>
										<li>1. Navigate to the Approve Analytics tab.</li>
										<li>2. Click on the Show Submitted Analytics button and review the list of analytics awaiting approval.</li>
										<li>3. For each entry, you can:</li>
										<ul className='ml-10 list-disc'>
											<li>Click Approve to accept the analytic.</li>
											<li>Click Reject to decline the analytic. This will also remove the analytic from the system.</li>
										</ul>
									</ol>
								</div>
							</li>
						</ul>
					</div>

					<div>
						<h2 className='guideH2'>2. Manage Reports</h2>
						<p>The Manage Reports page provides two key functionalities:</p>
						<ul>
							<li>
								<h3 className='guideH3'>2.1 Create Report</h3>
								<div className='ml-5'>
									<p><span className='font-semibold'>Purpose:</span> Create reports by selecting analytic graphs or charts.</p>
									<p className='font-semibold'>Steps:</p>
									<ol>
										<li>1. Click the Create Report button.</li>
										<li>2. Enter the Report Name.</li>
										<li>3. Select the analytics you want to include in the report.</li>
										<li>4. Provide the following details:</li>
										<ul className='ml-10 list-disc'>
											<li>Heading for each analytic.</li>
											<li>Description for each analytic.</li>
										</ul>
										<li>4. Click Show Preview Button to finalize the report and click Generate Report to save the report to the system.</li>
									</ol>
								</div>
							</li>
							<li>
								<h3 className='guideH3'>2.2 Manage Reports</h3>
								<div className='ml-5'>
									<p><span className='font-semibold'>Purpose:</span> View or delete previously generated reports.</p>
									<p className='font-semibold'>Steps:</p>
									<ol>
										<li>1. Click the Manage Reports button.</li>
										<li>2. View the list of existing reports.</li>
										<li>3. For each report, you can:</li>
										<ul className='ml-10 list-disc'>
											<li>Click View to open and review the report.</li>
											<li>Select a report to mark it for deletion.</li>
										</ul>
										<li>4. On clicking the Save Changes Button you can delete the selected reports.</li>
									</ol>
								</div>
							</li>
						</ul>
					</div>

					<div>
						<h2 className='guideH2'>3. Manage Users</h2>
						<p>The Manage Users page allows you to handle staff authentication and user accounts.</p>
						<ul>
							<li>
								<h3 className='guideH3'>3.1 Generate UUID</h3>
								<div className='ml-5'>
									<p><span className='font-semibold'>Purpose:</span> Generate unique identifiers (UUIDs) for staff authentication.</p>
									<p className='font-semibold'>Steps:</p>
									<ol>
										<li>1. Click the Generate UUID button.</li>
										<li>2. The system will generate a new UUID.</li>
										<li>3. Share this UUID with the intended staff member for their authentication during sign-in.</li>
									</ol>
								</div>
							</li>
							<li>
								<h3 className='guideH3'>3.2 Manage Existing Users</h3>
								<div className='ml-5'>
									<p><span className='font-semibold'>Purpose:</span> View or remove existing user accounts.</p>
									<p className='font-semibold'>Steps:</p>
									<ol>
										<li>1. Review the table displaying all existing users.</li>
										<li>2. You can select any user(s) to mark them for removal from the system.</li>
									</ol>
								</div>
							</li>
						</ul>
					</div>

					<div><h2 className='guideH2'>General Tips</h2>
						<ul className='list-disc ml-5'>
							<li>Double-check data and selections before submitting any changes or updates.</li>
							<li>For assistance, contact us directly through <Link to={'/'} className='cursor-pointer'><em>arg.com</em></Link>.</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	)
}

export default InstitutionHomeContainer